Repository vxcontrol/soldr, pull requests merged in 2022-12, with the labels that each got.

#25 fix: yara scanner validation
  web/libs/styles/src/lib/design-tokens/legacy-2017/element-ui/_element-variables.scss
  web/libs/styles/src/lib/design-tokens/pt-2022/element-ui/_element-variables.scss
  web/libs/styles/src/lib/element-ui/components/checkbox.scss
  web/libs/styles/src/lib/element-ui/components/loading.scss
  web/libs/styles/src/lib/element-ui/fonts/element-icons.ttf
  web/libs/styles/src/lib/element-ui/fonts/element-icons.woff
  web/libs/styles/src/lib/overriden-vue/_overriden-vue.theme.scss
Labels: bug

#28 upload agent binary fix, listen api on all interfaces
  .env.template
  Makefile
Labels: enhancement

#35 fix(ui): secure params rendering with different widget types
  web/libs/shared/src/lib/components/secure-module-config/secure-module-config.component.html
  web/libs/shared/src/lib/components/secure-module-config/secure-module-config.component.ts
Labels: bug, ui

#36 fix(ui): error on saving module after removing all params
  web/libs/shared/src/lib/utils/get-empty-schema.ts
  web/libs/store/modules/src/lib/edit/module-edit.reducer.ts
Labels: bug, ui

#37 fix(ui): text is not visible on the module configuration tab
  web/libs/styles/src/lib/element-ui/_element-ui-components.theme.scss
  web/libs/styles/src/lib/element-ui/components/switch.scss
Labels: bug, ui

#38 fix(ui): event config, conflict groups, screen flashing
  web/libs/features/policies/src/lib/services/link-policy.facade.service.ts
  web/libs/shared/src/lib/components/modules-config/modules-config.component.html
  web/libs/shared/src/lib/components/ncform-wrapper/ncform-wrapper.component.ts
  web/libs/styles/src/lib/overriden-vue/_overriden-vue.scss
Labels: bug, ui

#39 fix(ui): allow spaces in localization values in system module (#32)
  web/libs/features/modules/src/lib/components/edit-localization-section/edit-localization-section.component.html
Labels: bug, ui

#41 [issue-2] add templates
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-enhancement.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SAVED_REPLIES.md
Labels: enhancement

#40 Add observability stack for SOLDR
  .env.template
  README.md
  cmd/agent/main.go
  cmd/api/main.go
  cmd/server/main.go
  docker-compose.yml
  go.mod
  go.sum
  internal/lua/state_test.go
  internal/observability/client_test.go
  internal/observability/metric_test.go
  internal/observability/obs.go
  internal/observability/trace.go
  internal/observability/trace_test.go
Labels: enhancement, observability
