Repository vxcontrol/soldr, pull requests merged in 2023-02, with the labels that each got.

#84 fix(ui):consistency in policies grid is hidden by default
  web/libs/features/policies/src/lib/routes/policies-page/policies-page.component.html
  web/libs/shared/src/lib/components/policies-grid/policies-grid.component.html
Labels: bug, ui

#85 fix(ui): change save module dialog, add splitter in assigning action master dialog title
  web/libs/features/modules/src/lib/routes/edit-module-page/edit-module-page.component.ts
  web/libs/i18n-resources/en-US/modules.json
  web/libs/i18n-resources/en-US/shared.json
  web/libs/i18n-resources/ru-RU/modules.json
Labels: bug, ui

#87 fix(ui): incorrect work of file synchronization in editor of system m…
  web/libs/features/modules/src/lib/components/edit-file-modal/edit-file-modal.component.html
  web/libs/features/modules/src/lib/components/edit-file-modal/edit-file-modal.component.scss
  web/libs/features/modules/src/lib/components/edit-file-modal/edit-file-modal.component.ts
Labels: bug, ui

#90 fix(ui): updated npm dependencies
  web/.yarnrc
  web/libs/shared/src/lib/components/grid/grid.component.html
  web/libs/shared/src/lib/components/grid/grid.component.ts
  web/libs/shared/src/lib/directives/ag-grid/template-column.directive.ts
  web/migrations.json
  web/package-lock.json
  web/package.json
Labels: ui

#91 fix(ui): removed scroll on assigning actions
  web/libs/styles/src/lib/ag-grid/_ag-grid-theme.scss
Labels: bug

#93 fix(ui): small fixes vue grid
  web/libs/features/modules-interactivity/src/lib/components/grid/grid.component.js
  web/libs/styles/src/lib/overriden-vue/_overriden-vue.theme.scss
Labels: ui

#92 fix(ui): tags & modules validation
  web/libs/features/modules/src/lib/components/create-module-modal/create-module-modal.component.html
  web/libs/features/modules/src/lib/components/create-module-modal/create-module-modal.component.ts
  web/libs/shared/src/lib/components/autocomplete-tags/autocomplete-tags.component.html
  web/libs/shared/src/lib/components/autocomplete-tags/autocomplete-tags.component.ts
Labels: bug, ui

#94 fix(ui): cannot add the "Write to DB" action for module events throug…
  web/libs/shared/src/lib/components/assigning-actions-master/assigning-actions-master.component.ts
  web/libs/shared/src/lib/components/assigning-actions-to-event/assigning-actions-to-event.component.ts
  web/libs/shared/src/lib/types/actions.ts
Labels: bug, ui
