Repository vxcontrol/soldr, pull requests merged in 2023-01, with the labels that each got.

#44 fix: hint "edit in policy" and availability of buttons in the module configuration
  web/libs/features/agents/src/lib/routes/agent-module-page/agent-module-page.component.html
  web/libs/features/agents/src/lib/routes/agent-module-page/agent-module-page.component.ts
  web/libs/features/groups/src/lib/routes/group-module-page/group-module-page.component.html
  web/libs/features/groups/src/lib/routes/group-module-page/group-module-page.component.ts
  web/libs/features/modules-interactivity/src/lib/components/module-page/module-page.component.html
  web/libs/features/modules-interactivity/src/lib/components/module-page/module-page.component.ts
  web/libs/features/policies/src/lib/routes/policy-module-page/policy-module-page.component.html
  web/libs/features/policies/src/lib/routes/policy-module-page/policy-module-page.component.ts
  web/libs/shared/src/lib/components/action-details-panel/action-details-panel.component.html
  web/libs/shared/src/lib/components/action-details-panel/action-details-panel.component.ts
  web/libs/shared/src/lib/components/event-details-panel/event-details-panel.component.html
  web/libs/shared/src/lib/components/event-details-panel/event-details-panel.component.ts
  web/libs/shared/src/lib/components/module-config/module-config.component.html
  web/libs/shared/src/lib/components/module-config/module-config.component.ts
  web/libs/store/modules-instances/src/lib/modules-instances.actions.ts
  web/libs/store/modules-instances/src/lib/modules-instances.effects.ts
  web/libs/store/modules-instances/src/lib/modules-instances.facade.service.ts
  web/libs/store/modules-instances/src/lib/modules-instances.reducer.ts
  web/libs/store/modules-instances/src/lib/modules-instances.selectors.ts
Labels: bug, ui

#45 fix: save event changes in module configuration
  web/libs/store/policies/src/lib/policies.reducer.ts
Labels: bug, ui

#48 fix(ui): invalid monaco editor loader
  web/angular.json
Labels: bug, ui

#43 Add vxproto subscriptions (topics)
  internal/lua/module.go
  internal/lua/module_test.go
  internal/vxproto/module.go
  internal/vxproto/proto.go
  internal/vxproto/proto_test.go
Labels: enhancement

#55 Add vxproto connection linked to group lua state
  .vscode/launch.json
  Makefile
  build/package/agent/build-install-linux.sh
  build/package/agent/build-windows-386.sh
  build/package/agent/build-windows-amd64.sh
  build/package/agent/build.sh
  build/package/api/build-local.sh
  build/package/dbmigrate/entrypoint.sh
  build/package/server/build.sh
  db/server/migrations/0002_aggregate_conn_type.sql
  internal/app/api/docs/docs.go
  internal/app/api/docs/swagger.json
  internal/app/api/docs/swagger.yaml
  internal/app/api/models/binaries.go
  internal/app/api/models/proto.go
  internal/app/api/server/middleware.go
  internal/app/api/server/proto/proto.go
  internal/app/api/server/proto/vm/vm.go
  internal/app/api/server/router.go
  internal/app/api/utils/utils.go
  internal/app/api/worker/module_syncer.go
  internal/app/server/mmodule/hardening/v1/abher/abh_list.go
  internal/app/server/mmodule/hardening/v1/abher/abh_list_test.go
  internal/app/server/mmodule/hardening/v1/abher/abher.go
  internal/app/server/mmodule/hardening/v1/validator/ainfo/ainfo.go
  internal/app/server/mmodule/hardening/v1/validator/conn.go
  internal/app/server/mmodule/mmodule.go
  internal/vxproto/agent.go
  internal/vxproto/proto_test.go
  internal/vxproto/ws_client.go
  internal/vxproto/ws_server.go
  scripts/certs_writer/certs_suite.go
  scripts/gen-certs.sh
  web/libs/features/groups/src/lib/routes/group-module-page/group-module-page.component.html
  web/libs/features/modules-interactivity/src/lib/components/module-interactive-part/module-interactive-part.component.ts
  web/libs/features/modules-interactivity/src/lib/components/module-page/module-page.component.ts
  web/libs/features/modules-interactivity/src/lib/utils/proto.js
Labels: enhancement

#56 Use global DB instance as service dependency
  internal/app/api/server/private/binaries.go
  internal/app/api/server/private/events.go
  internal/app/api/server/private/groups.go
  internal/app/api/server/private/modules.go
  internal/app/api/server/private/options.go
  internal/app/api/server/private/policies.go
  internal/app/api/server/private/porting.go
  internal/app/api/server/private/roles.go
  internal/app/api/server/private/services.go
  internal/app/api/server/private/tags.go
  internal/app/api/server/private/tenants.go
  internal/app/api/server/private/upgrades.go
  internal/app/api/server/private/users.go
  internal/app/api/server/private/versions.go
  internal/app/api/server/router.go
Labels: enhancement

#62 fix(ui): request of all agents optimized
  internal/app/api/docs/docs.go
  internal/app/api/docs/swagger.json
  internal/app/api/docs/swagger.yaml
  internal/app/api/server/events/poller.go
  internal/app/api/server/private/binaries.go
  internal/app/api/server/private/modules.go
  internal/app/api/worker/module_syncer.go
  web/libs/api/src/lib/dto/events.ts
  web/libs/features/groups/src/lib/routes/group-module-page/group-module-page.component.ts
  web/libs/features/groups/src/lib/routes/group-page/group-page.component.ts
  web/libs/features/policies/src/lib/routes/policy-module-page/policy-module-page.component.ts
  web/libs/features/policies/src/lib/routes/policy-page/policy-page.component.ts
  web/libs/shared/src/lib/components/events-grid/events-grid.component.html
  web/libs/store/groups/src/lib/groups.actions.ts
  web/libs/store/groups/src/lib/groups.effects.ts
  web/libs/store/groups/src/lib/groups.facade.ts
  web/libs/store/groups/src/lib/groups.reducer.ts
  web/libs/store/groups/src/lib/groups.selectors.ts
  web/libs/store/modules-instances/src/lib/modules-instances.actions.ts
  web/libs/store/modules-instances/src/lib/modules-instances.effects.ts
  web/libs/store/modules-instances/src/lib/modules-instances.facade.service.ts
  web/libs/store/modules-instances/src/lib/modules-instances.reducer.ts
  web/libs/store/modules-instances/src/lib/modules-instances.selectors.ts
  web/libs/store/policies/src/lib/policies.actions.ts
  web/libs/store/policies/src/lib/policies.effects.ts
  web/libs/store/policies/src/lib/policies.facade.ts
  web/libs/store/policies/src/lib/policies.reducer.ts
  web/libs/store/policies/src/lib/policies.selectors.ts
Labels: bug, ui

#61 return password_change_required flag
  db/api/migrations/0002_add_user_password_change_flag.sql
  db/api/seed.sql
  internal/app/api/docs/docs.go
  internal/app/api/docs/swagger.json
  internal/app/api/docs/swagger.yaml
  internal/app/api/models/users.go
  internal/app/api/server/private/users.go
Labels: enhancement

#63 fix lua modules tests: issue due to merge typo
  internal/lua/module_test.go
Labels: bug

#57 Use agent server DB as service dependency
  cmd/api/main.go
  internal/app/api/client/agent_server.go
  internal/app/api/server/context/context.go
  internal/app/api/server/middleware.go
  internal/app/api/server/permissions.go
  internal/app/api/server/private/agents.go
  internal/app/api/server/private/binaries.go
  internal/app/api/server/private/events.go
  internal/app/api/server/private/groups.go
  internal/app/api/server/private/modules.go
  internal/app/api/server/private/notifications.go
  internal/app/api/server/private/options.go
  internal/app/api/server/private/policies.go
  internal/app/api/server/private/porting.go
  internal/app/api/server/private/proto.go
  internal/app/api/server/private/roles.go
  internal/app/api/server/private/services.go
  internal/app/api/server/private/tags.go
  internal/app/api/server/private/tenants.go
  internal/app/api/server/private/upgrades.go
  internal/app/api/server/private/users.go
  internal/app/api/server/private/versions.go
  internal/app/api/server/proto/proto.go
  internal/app/api/server/public/auth.go
  internal/app/api/server/public/info.go
  internal/app/api/server/response/http.go
  internal/app/api/server/response/list.go
  internal/app/api/server/router.go
  internal/app/api/storage/mem/connection.go
  internal/app/api/utils/utils.go
  internal/app/api/utils/utils_test.go
  scripts/errgen/Makefile
Labels: enhancement

#66 fix(ui): fixed removing event actions
  web/libs/features/modules/src/lib/components/edit-dependencies-section/edit-dependencies-section.component.html
  web/libs/features/modules/src/lib/components/edit-secure-config-section/edit-secure-config-section.component.html
  web/libs/shared/src/lib/components/assigning-actions-master/assigning-actions-master.component.ts
  web/libs/shared/src/lib/components/assigning-actions-to-event/assigning-actions-to-event.component.ts
Labels: bug, ui

#67 fix(ui): doesn't work saving in system module in safari
  web/libs/features/modules/src/lib/components/edit-actions-section/edit-actions-section.component.ts
  web/libs/features/modules/src/lib/components/edit-changelog-section/edit-changelog-section.component.ts
  web/libs/features/modules/src/lib/components/edit-config-section/edit-config-section.component.ts
  web/libs/features/modules/src/lib/components/edit-dependencies-section/edit-dependencies-section.component.ts
  web/libs/features/modules/src/lib/components/edit-events-section/edit-events-section.component.ts
  web/libs/features/modules/src/lib/components/edit-fields-section/edit-fields-section.component.ts
  web/libs/features/modules/src/lib/components/edit-general-section/edit-general-section.component.ts
  web/libs/features/modules/src/lib/components/edit-localization-section/edit-localization-section.component.ts
  web/libs/features/modules/src/lib/components/edit-secure-config-section/edit-secure-config-section.component.ts
Labels: bug, ui

#68 fix(ui): unresolved agent version dependency appears as resolved
  web/libs/shared/src/lib/components/modules-config/modules-config.component.ts
Labels: bug, ui

#69 fix(ui): restored dark theme monaco
  web/libs/core/src/lib/services/monaco.service.ts
Labels: bug, ui

#70 rework user action logger
  Makefile
  cmd/api/main.go
  pkg/app/api/server/middleware.go
  pkg/app/api/server/permissions.go
  pkg/app/api/server/private/agents.go
  pkg/app/api/server/private/binaries.go
  pkg/app/api/server/private/events.go
  pkg/app/api/server/private/groups.go
  pkg/app/api/server/private/modules.go
  pkg/app/api/server/private/notifications.go
  pkg/app/api/server/private/options.go
  pkg/app/api/server/private/policies.go
  pkg/app/api/server/private/porting.go
  pkg/app/api/server/private/proto.go
  pkg/app/api/server/private/roles.go
  pkg/app/api/server/private/services.go
  pkg/app/api/server/private/tags.go
  pkg/app/api/server/private/tenants.go
  pkg/app/api/server/private/upgrades.go
  pkg/app/api/server/private/users.go
  pkg/app/api/server/private/versions.go
  pkg/app/api/server/proto/proto.go
  pkg/app/api/server/public/auth.go
  pkg/app/api/server/public/info.go
  pkg/app/api/server/response/http.go
  pkg/app/api/server/router.go
  pkg/app/api/server/server_test.go
  pkg/app/api/user_action/log.go
  pkg/app/api/user_action/user_action.go
  pkg/app/api/utils/utils.go
  pkg/app/api/utils/utils_test.go
Labels: enhancement

#71 Refactor logging
  .env.template
  .vscode/launch.json
  Makefile
  build/package/dbmigrate/entrypoint.sh
  cmd/api/main.go
  cmd/server/main.go
  db/api/migrations/0002_add_user_password_change_flag.sql
  go.mod
  go.sum
  pkg/app/api/client/agent_server.go
  pkg/app/api/server/events/poller.go
  pkg/app/api/server/middleware.go
  pkg/app/api/server/private/agents.go
  pkg/app/api/server/private/binaries.go
  pkg/app/api/server/private/groups.go
  pkg/app/api/server/private/modules.go
  pkg/app/api/server/private/notifications.go
  pkg/app/api/server/private/policies.go
  pkg/app/api/server/private/porting.go
  pkg/app/api/server/private/services.go
  pkg/app/api/server/private/tenants.go
  pkg/app/api/server/private/upgrades.go
  pkg/app/api/server/private/users.go
  pkg/app/api/server/proto/proto.go
  pkg/app/api/server/router.go
  pkg/app/api/user_action/log.go
  pkg/app/api/user_action/user_action.go
  pkg/app/api/utils/utils.go
  pkg/app/api/worker/module_syncer.go
  pkg/log/context.go
  pkg/log/log.go
  pkg/logger/gorm.go
  pkg/logger/logger.go
  pkg/storage/mysql/mysql.go
Labels: enhancement

#77 Add max syncing agents and migration path config parameters to server
  cmd/server/main.go
  pkg/app/server/config/config.go
  pkg/app/server/mmodule/mmodule.go
  pkg/app/server/mmodule/net.go
Labels: enhancement

#78 add modules cache for api
  cmd/api/main.go
  pkg/app/api/server/errors.yml
  pkg/app/api/server/private/agents.go
  pkg/app/api/server/private/groups.go
  pkg/app/api/server/private/modules.go
  pkg/app/api/server/private/services.go
  pkg/app/api/server/response/list.go
  pkg/app/api/server/router.go
  pkg/app/api/storage/module.go
Labels: enhancement

#80 Save module's files checksums and validate when updating agents modules
  cmd/agent/main.go
  db/server/migrations/0003_minio_modules_data_checksum.sql
  pkg/app/api/models/modules.go
  pkg/app/api/modules/modules.go
  pkg/app/api/modules/modules_test.go
  pkg/app/api/server/private/modules.go
  pkg/app/api/server/private/options.go
  pkg/app/api/server/private/policies.go
  pkg/app/api/server/private/porting.go
  pkg/app/api/server/private/upgrades.go
  pkg/app/api/worker/module_syncer.go
  pkg/app/server/mmodule/net.go
  pkg/controller/controller.go
  pkg/controller/files.go
  pkg/controller/loader.go
  pkg/loader/structs.go
  pkg/protoagent/agent.pb.go
  pkg/protoagent/agent.proto
  pkg/protoagent/utils.go
Labels: enhancement

#81 fix(ui): invalid fields count and validation long names
  web/libs/features/agents/src/lib/components/edit-agent-modal/edit-agent-modal.component.html
  web/libs/features/groups/src/lib/components/edit-group-modal/edit-group-modal.component.html
  web/libs/features/modules/src/lib/components/toggle-item/toggle-item.component.ts
  web/libs/features/policies/src/lib/components/edit-policy-modal/edit-policy-modal.component.html
  web/libs/i18n-resources/en-US/common.json
  web/libs/i18n-resources/ru-RU/common.json
Labels: bug, ui

#82 add operators to table
  pkg/app/api/storage/table.go
  web/libs/store/shared/src/lib/shared.effects.ts
Labels: enhancement

#83 Refactoring after sync
  Makefile
  build/package/dbmigrate/entrypoint.sh
  db/api/seed.sql
  pkg/app/api/modules/modules.go
  pkg/app/api/server/private/helpers.go
  pkg/app/api/server/private/modules.go
  pkg/app/api/server/private/options.go
  pkg/app/api/server/private/policies.go
  pkg/app/api/server/private/porting.go
  pkg/app/api/server/private/upgrades.go
  pkg/app/api/worker/module_syncer.go
  pkg/controller/controller.go
Labels: bug
